<?php

namespace DiscountBundle\Repository;

use DiscountBundle\Entity\PopularShopGroup;
use Doctrine\ORM\EntityRepository;

/**
 * PopularShopGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PopularShopGroupRepository extends EntityRepository
{
    public function getGroup($groupId)
    {
        $connection = $this->getEntityManager()->getConnection();
        $stmt = $connection->executeQuery('SELECT * FROM feature_groups_main_page WHERE group_id = :groupId  ORDER BY sort', [
            'groupId' => $groupId
        ]);

        return $stmt->fetchAll();
    }

}
